{
 "title": "My dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPULA 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPULA 1" }
   ]
  },
  {
   "title": "CPULA5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_load5", "legendFormat": "CPULA 5" }
   ]
  },
  {
   "title": "CPULA 15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_load15", "legendFormat": "CPULA 15" }
   ]
  },
  {
   "title": "RAM active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_Active_bytes", "legendFormat": "RAM active" }
   ]
  },
  {
   "title": "RAM total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "FS size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/root\", fstype=\"erofs\", instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\"}",
     "legendFormat": "device=\"/dev/root\""
    }
   ]
  },
  {
   "title": "RAM free",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  }
 ]
}