---
local:
  hosts:
    localhost:
      ansible_host: localhost
      ansible_connection: local
runner:
  hosts:
    gitlab-runner:
      ansible_host: 89.169.154.74
  vars:
    ansible_connection_type: paramiko
    ansible_user: eurus_cloud
