version: "3"

services:
  centos7:
    image: centos:7
    container_name: centos7
    restart: on-failure
    command: tail -f /dev/null

  ubuntu:
    container_name: ubuntu
    build:
      dockerfile: Dockerfile
    restart: on-failure
    command: tail -f /dev/null